config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shogi#dir'
  get ':id', to: 'shogi#view', id: /\w+\.log/, as: 'shogi_view'
  get 'partial/:id/:moves', to: 'shogi#board', id: /\w+\.log/, moves: /\d+/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shogi_controller.rb
require './lib/shogi'

class ShogiController < ApplicationController
  def dir
    @files = Dir.glob(File.join(Rails.configuration.log_path, '*.log')).map do |e|
      {
          path: e,
          name: File.basename(e),
          mtime: File.mtime(e),
          size: File.size(e),
      }
    end
  end

  def view
    str = IO.read(File.join(Rails.configuration.log_path, params[:id]))
    @name_black = str[/^Name\+:(.+)$/, 1]
    @name_white = str[/^Name-:(.+)$/, 1]
    @moves = str.lines.select {|e| /^[+-]\d{4}\D{2}/ === e}.map {|e| Shogi::Move.parse(e)}
    @pos = Shogi::Position.new
    @last = nil
    @moves.each do |e|
      @pos.do_move(e)
      @last = e
    end
  end

  def board
    str = IO.read(File.join(Rails.configuration.log_path, params[:id]))
    @moves = str.lines.select {|e| /^[+-]\d{4}\D{2}/ === e}.map {|e| Shogi::Move.parse(e)}
    @pos = Shogi::Position.new
    @last = nil
    @moves.each.with_index(1) do |e, i|
      @pos.do_move(e)
      @last = e
      break if i >= params[:moves].to_i
    end
    render partial: "board"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shogi_helper.rb
module ShogiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Tui</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shogi/_board.html.slim
div.capturedPiece-white
  span style="writing-mode: vertical-rl; font-size: 3rem; transform: rotate(0.5turn);"
    = @pos.hand_white.map(&:to_s).join

div
  table.board
    tbody
      tr
        - (1..9).reverse_each do |n|
          th = n
      - (1..9).each do |rank|
        tr
          - (1..9).reverse_each do |file|
            - piece = @pos[file, rank]
            - highlight = @last.to == [file, rank] ? 'highlight' : nil
            = content_tag(:td, piece.white? ? content_tag(:span, piece.to_s, class: 'rotate') : piece.to_s, class: highlight)
          th = ['〇', '一', '二', '三', '四', '五', '六', '七', '八', '九'][rank]

div.capturedPiece-black
  span style="writing-mode: vertical-rl; text-align:right; font-size: 3rem;"
    = @pos.hand_black.map(&:to_s).join

app/views/shogi/dir.html.slim
table#myTable
  thead
    tr
      th name
      th bytes
      th mtime
  tbody
    - @files.each do |file|
      tr
        td = link_to(file[:name], shogi_view_path(file[:name]))
        td = file[:size]
        td = file[:mtime]

app/views/shogi/index.html.erb
<table>
  <tbody>
  <tr>
    <th>name</th>
    <th>bytes</th>
  </tr>

  <% @files.each do |file| %>
    <tr>
      <td><%= link_to file[:name], hogee_path(file[:name]) %></td>
      <td><%= file[:size] %></td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/shogi/view.html.slim
p ▲#{@name_black} △#{@name_white}

div.flex-container
  div
    p 棋譜
    select#kifu data-filename=params[:id] size=30 autofocus=true
      - @moves.each.with_index(1) do |move, i|
        option value=i selected=(i == @moves.size) #{i} #{move}

  div.flex-container#board
    = render partial: 'board'